### ISSUE TITLE
can you create its executable version

### ISSUE THREAD

**Issue by denim27** [meeranh/recycleMe#1]
can you create its executable version

**Comment by meeranh** [comment]
You can find it in the releases section in this repository:
https://github.com/meeranh/recycleMe/releases/tag/v0.1

**Comment by denim27** [comment]
sir .exe is not working. window is saying this is a virus

**Comment by meeranh** [comment]
I think you are getting a virus warning because it creates a file on the system to write the humanized text. So the write operation is probably flagged as malicious (its a false positive).

You can put the executable into VirusTotal and verify it.  [This](https://www.virustotal.com/gui/file/a77347c06761aeb08c9255eef764dd744a1a34bdfc04c31bde400927cdc9fa10/detection) is the link to the scan.

You can either whitelist this binary in your antivirus software or maybe you could even clone this repo and run `go run main.go` after running `go mod tidy`.

**Comment by denim27** [comment]
nothing happens when i run it. its not working

**Comment by denim27** [comment]
not working plz help me to try this

**Comment by denim27** [comment]
![errr](https://github.com/meeranh/recycleMe/assets/143706789/4626bfa2-6682-4fe1-bc01-a6730fdd8e70)

**Comment by denim27** [comment]
sir can you share your whatspp number i am in great need of this tool. want to check whether it will serve my purpose or not?

**Comment by denim27** [comment]
hello kindly reply backkkkk

**Comment by denim27** [comment]
Hassan Meeran - Product Manager - Analytics and Insights

Chennai, Tamil Nadu, India · Product Manager - Analytics and Insights · Datagamz
Hassan Meeran. Product Manager at Datagamz. Datagamz Vel tech Engineering college. Chennai, Tamil Nadu, India.

are you working as product manager

**Comment by denim27** [comment]
![90909090](https://github.com/meeranh/recycleMe/assets/143706789/58fad4e6-3a8f-4eda-838b-27c8e4a4fb61)
i dont know how to add binary

**Comment by meeranh** [comment]
Bro do you need this project for a university assignment? I can help if so. Give me the details I can set everything up for you.

Btw open a Powershell and drag and drop the EXE file and press enter. Also if you get the "Windows protected your PC" warning you can press "Info" and click on "Run anyway" and it should work.

**Comment by denim27** [comment]
Yes sir i am reasrch schloar when i write paper using ai tool. Editor desk reject that due to ai plag. Please help me.kindly guve your whatspp .its difficult to be online on github always.plz help me. Plzz

**Comment by denim27** [comment]
I just want to remove 100% ai from my paper. I am unable to run your project on my laptop due to my lower learning curve in this field. I dnt know whether your project will really convert ai into human or not.

**Comment by meeranh** [comment]
I also don't have time because I also have to submit my research paper this month and it is taking too much of my time. Ill try to give you a solution.
Btw not giving my WhatsApp because of privacy issues 🥲

What is the word count of your paper and when is the deadline?

**Comment by denim27** [comment]
Sir if dont help then leave it. Sorry to bother you. My master taught me Helping hands are always better than praying lips. Once again sorry. Its my bad luck that you are unable to solve my problem😔

**Comment by denim27** [comment]
![111111111111111111](https://github.com/meeranh/recycleMe/assets/143706789/d2738a0a-aa9f-42fe-a161-4c8d922258d4)
wasted my whole working day. but its not working for me

**Comment by meeranh** [comment]
Hello can you type `recycleMe` and actually drag and drop the MD file to your terminal? This way you will get the correct file path. Also you have to have an actual MD file (or even a TXT file will work). Its just a file with your research paper's plain text. I think you have properly run the `recycleMe` command, but have not properly put the correct filepath. If you drag and drop your file to the terminal, you will get the correct file path. Can you do that and let me know what happens?

**Comment by denim27** [comment]
Its not working. I converted my paper file .md file then run. But it shows 0 ai plag. Generate humanized content which is 100% similar to my original file..its just wasting time. And you dont want to resolve. Uts difficult to everytime pitch on github. Either share your telegram

**Comment by denim27** [comment]
Problem is not about path .problem is your tool is not working as you presented in video tutorial. Plz help to solve my problem by today. Otherwise i will never disturb you onward. Bye

**Comment by meeranh** [comment]
Hey bro I checked it on my machine and it is working for me. There might be a problem in how you generate your MD file. If you are using a Word file, copy all the text content to a TXT file and pass that TXT file to the program. It should work.

Also, this program uses [ZeroGPT](https://www.zerogpt.com) to detect AI content. So just check if your paper is being flagged as AI in ZeroGPT. I have attached an example MD file that gets flagged for AI so you can check.
[AI.md](https://github.com/meeranh/recycleMe/files/14946711/AI.md)

**Comment by denim27** [comment]
Sir its not working for me. I have already sent you today screenshot. Is there any other way to bypass ai plag. Turnitin is hell. I am unable to get my paper published

**Comment by denim27** [comment]
i think i have to humanize ai flag content manualy whcih is very pathetic . its better shut down all ai tools and write what mind says.
